spring:
  application:
    name: payment-service
  cloud:
    stream:
      function:
        definition : paymentProcessor
      bindings:
        paymentProcessor-in-0 :
          destination: order-event
        paymentProcessor-out-0:
          destination: payment-event


server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
